routes/web.php
<?php

use App\Http\Controllers\DonDatController;
use App\Http\Controllers\SanPhamController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/sanpham');
});

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('sanpham')->name('sanpham.')->group(function () {
    $class = SanPhamController::class;
    Route::get('/', [$class, 'index'])->name('index');
    Route::get('/create', [$class, 'create'])->name('create');
    Route::post('/', [$class, 'store'])->name('store');
    //Route::get('/{sanpham}', [$class, 'show'])->name('show');
    Route::put('/{sanpham}', [$class, 'update'])->name('update');
    Route::delete('/{sanpham}', [$class, 'destroy'])->name('destroy');
    Route::get('/{sanpham}/edit', [$class, 'edit'])->name('edit');
});

Route::prefix('dondat')->name('dondat.')->group(function () {
    $class = DonDatController::class;
    Route::get('/', [$class, 'index'])->name('index');
    Route::get('/create', [$class, 'create'])->name('create');
    Route::post('/', [$class, 'store'])->name('store');
    Route::get('/{dondat}', [$class, 'show'])->name('show');
    Route::put('/{dondat}', [$class, 'update'])->name('update');
    Route::delete('/{dondat}', [$class, 'destroy'])->name('destroy');
    Route::get('/{dondat}/edit', [$class, 'edit'])->name('edit');
    Route::post('/them_chi_tiet_don_dat', [$class, 'them_chi_tiet_don_dat'])->name('them_chi_tiet_don_dat');
    Route::delete('/delete/{id}', [$class, 'delete_chi_tiet_don_dat'])->name('delete_chi_tiet_don_dat');
});

app/Models/SanPham.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class SanPham extends Model
{
    use HasFactory;

    protected $table = 'san_phams';

    protected $fillable = [
        'id',
        'ma_thuong_hieu',
        'ma_loai_san_pham',
        'ten',
        'hinh_anh',
        'don_vi',
        'don_gia_nhap',
        'don_gia_ban',
        'ma_san_pham_cha'
    ];

    public function getImage()
    {
        return asset("images/sanphams/".$this->hinh_anh);
    }

    public function saveSanPham(Request $request)
    {
        $data = [
            'ma_thuong_hieu' => $request->input('ma_thuong_hieu'),
            'ma_loai_san_pham' => $request->input('ma_loai_san_pham'),
            'ten' => $request->input('ten'),
            'don_vi' => $request->input('don_vi'),
            'don_gia_nhap' => $request->input('don_gia_nhap'),
            'don_gia_ban' => $request->input('don_gia_ban'),
            'ma_san_pham_cha' => $request->input('ma_san_pham_cha'),
        ];

        //$data['hinh_anh'] = $this->saveFile($request, 'hinh_anh');

        if($request->hasFile('hinh_anh'))
        {
            $data['hinh_anh'] = $this->saveFile($request, 'hinh_anh');
        }
        else {
            $data['hinh_anh'] = 'null';
        }

        $sanpham = $this->create($data);

        return $sanpham;
    }

    private function saveFile(Request $request, string $file)
    {
        $file = $request->file($file);
        $extension = $file->getClientOriginalExtension();
        $fileName = time() . '.' . $extension;
        $path = public_path().'/images/sanphams/';
        $file->move($path, $fileName);
        return $fileName;
    }

    public function deleteFile(string $path)
    {
        if(file_exists($path))
        {
            File::delete($path);
        }
    }

    public function updateSanPham(Request $request, SanPham $sanphams)
    {
        $sanphams->ma_thuong_hieu = $request->input('ma_thuong_hieu');
        $sanphams->ma_loai_san_pham = $request->input('descrima_loai_san_phamption');
        $sanphams->ten = $request->input('ten');
        $sanphams->don_vi = $request->input('don_vi');
        $sanphams->don_gia_nhap = $request->input('don_gia_nhap');
        $sanphams->don_gia_ban = $request->input('don_gia_ban');
        $sanphams->ma_san_pham_cha = $request->input('ma_san_pham_cha');

        if($request->hasFile('hinh_anh'))
        {
            $path = public_path().'/images/sanphams/' . $sanphams->hinh_anh;
            $this->deleteFile($path);
            $sanphams['hinh_anh'] = $this->saveFile($request, 'hinh_anh');
        }
        else {
            $sanphams['hinh_anh'] = 'null';
        }

        $sanphams->save();
    }

    public function search(array $data)
    {
        $ten_sp = array_key_exists('key', $data) ? $data['key'] : null;
        $loai_sp = array_key_exists('loai_sp', $data) ? $data['loai_sp'] : null;

        return $this
                    ->SearchTenSP($ten_sp)
                    //->SearchLoaiSP($loai_sp)
                    ->latest('id')
                    ->paginate(array_key_exists('number', $data) ? $data['number'] : 5);
    }

    public function scopeSearchTenSP($query, $ten_sp)
    {
        return $query->where('ten', 'like', '%' . $ten_sp . '%');
    }

    public function scopeSearchLoaiSP($query, $loai_sp)
    {
        return $query->where('ma_loai_san_pham', 'like', '%' . $loai_sp . '%');
    }
}

app/Http/Controllers/SanPhamController.php
<?php

namespace App\Http\Controllers;

use App\Models\LoaiSanPham;
use App\Models\SanPham;
use App\Models\ThuongHieu;
use Illuminate\Http\Request;

class SanPhamController extends Controller
{
    protected $sanphams;

    public function __construct(SanPham $sanphams)
    {
        $this->sanphams = $sanphams;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $sanphams = $this->sanphams->search($request->all());
        return view('sanpham.index', compact('sanphams'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $thuong_hieus = ThuongHieu::all();
        $loai_san_phams = LoaiSanPham::all();
        return view('sanpham.create', compact('thuong_hieus', 'loai_san_phams'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'ten' => [
                'required',
            ],
            'don_gia_nhap' => 'nullable|numeric|min:100|max:2000',
            'don_gia_ban' => 'nullable|numeric|min:100|max:2000',
        ]);

        $this->sanphams->saveSanPham($request);
        //dd($request);
        return redirect(route('sanpham.index'))->with('success', 'Them thanh ccng !');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\SanPham  $sanPham
     * @return \Illuminate\Http\Response
     */
    public function show(SanPham $sanPham)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\SanPham  $sanPham
     * @return \Illuminate\Http\Response
     */
    public function edit(SanPham $sanpham)
    {
        return view('sanpham.edit', compact('sanPham'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\SanPham  $sanPham
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, SanPham $sanpham)
    {
        $sanpham->ma_thuong_hieu = $request->ma_thuong_hieu;
        $sanpham->ma_loai_san_pham = $request->ten_vaima_loai_san_pham_tro;
        $sanpham->ten = $request->ten;
        $sanpham->hinh_anh = $request->hinh_anh;
        $sanpham->don_vi = $request->don_vi;
        $sanpham->don_gia_nhap = $request->don_gia_nhap;
        $sanpham->don_gia_ban = $request->don_gia_ban;
        $sanpham->ma_san_pham_cha = $request->ma_san_pham_cha;
        $sanpham->save();

        return redirect()->route('sanpham.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\SanPham  $sanPham
     * @return \Illuminate\Http\Response
     */
    public function destroy(SanPham $sanpham)
    {
        $path = public_path().'/images/sanphams/' . $sanpham->hinh_anh;
        $sanpham->deleteFile($path);
        $sanpham->delete();
        return redirect()->route('sanpham.index');
    }
}

resources/views/sanpham/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                @if (session('success'))
                <div class="alert alert-success">
                    <p>{{ session('success') }}</p>
                </div>
                @endif
                <div class="card-header">Them moi san pham</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('sanpham.store') }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <label for="role" class="col-md-4 col-form-label text-md-right">Thuong hieu</label>
                            <div class="col-md-6">
                                <select name="ma_thuong_hieu" class="form-select form-select-sm">
                                    <option value="">Chon thuong hieu</option>
                                    @foreach ($thuong_hieus as $thuong_hieu)
                                        <option value="{{ $thuong_hieu->id }}">{{ $thuong_hieu->ten_thuong_hieu }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="role" class="col-md-4 col-form-label text-md-right">Loai san pham</label>
                            <div class="col-md-6">
                                <select name="ma_loai_san_pham" class="form-select form-select-sm">
                                    <option value="">Chon loai san pham</option>
                                    @foreach ($loai_san_phams as $loai_sp)
                                        <option value="{{ $loai_sp->id }}">{{ $loai_sp->ten_loai_san_pham }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Ten san pham</label>
                            <div class="col-md-6">
                                <input name="ten" type="text" value="{{ old('ten') }}" class="form-control @error('ten') is-invalid @enderror" >
                                @error('ten')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Hinh anh</label>
                            <div class="col-md-6">
                                <input id="hinh_anh" type="file" name="hinh_anh" class="form-control">
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Don vi</label>
                            <div class="col-md-6">
                                <input name="don_vi" type="text" value="{{ old('don_vi') }}" class="form-control @error('don_vi') is-invalid @enderror" >
                                @error('don_vi')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Don gia nhap</label>
                            <div class="col-md-6">
                                <input name="don_gia_nhap" type="text" value="{{ old('don_gia_nhap') }}" class="form-control @error('don_gia_nhap') is-invalid @enderror" >
                                @error('don_gia_nhap')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Don gia ban</label>
                            <div class="col-md-6">
                                <input name="don_gia_ban" type="text" value="{{ old('don_gia_ban') }}" class="form-control @error('don_gia_ban') is-invalid @enderror" >
                                @error('don_gia_ban')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Them
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/sanpham/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Chinh sua vai tro {{$vaitro->id}}</div>

                <div class="card-body">
                    <form action="{{ route('vaitro.update', $vaitro) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Ma to chuc</label>
                            <div class="col-md-6">
                                <input id="ma_to_chuc" type="text" class="form-control" name="ma_to_chuc" value="{{ $vaitro->ma_to_chuc }}" autofocus>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Ten vai tro</label>
                            <div class="col-md-6">
                                <input id="ten_vai_tro" type="text" class="form-control" name="ten_vai_tro" value="{{ $vaitro->ten_vai_tro }}" autofocus>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Mo ta</label>
                            <div class="col-md-6">
                                <input id="mo_ta" type="text" class="form-control" name="mo_ta" value="{{ $vaitro->mo_ta }}" autofocus>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Muc luong</label>
                            <div class="col-md-6">
                                <input id="muc_luong" type="text" class="form-control" name="muc_luong" value="{{ $vaitro->muc_luong }}" autofocus>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary">
                            Update
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/sanpham/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">

        <div class="col-md-12">
            <h1 class="mt-4">Quan ly San pham</h1>
            <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">Welcome to Quan ly San pham !!</li>
            </ol>
            <div class="card">
                <div class="card-header">
                    <a href="{{ route('sanpham.create') }}" class="btn btn-primary">Them moi san pham</a>
                </div>
                <form action="{{ route('sanpham.index') }}" method="GET" class="md-3 d-flex">
                    <input type="text" class="form-control" name="key" value="{{request('key')}}">
                    <button class="btn btn-primary" type="submit">Search</button>
                </form>
                <div class="card-body">

                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Thuong hieu</th>
                            <th scope="col">Loai san pham</th>
                            <th scope="col">Ten san pham</th>
                            <th scope="col">Hinh anh</th>
                            <th scope="col">Don vi</th>
                            <th scope="col">Don gia nhap</th>
                            <th scope="col">Don gia ban</th>
                            {{-- <th scope="col">Ma san pham cha</th> --}}
                            <th scope="col">Actions</th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($sanphams as $sp)
                            <tr>
                                <th scope="row">{{$sp->id}}</th>
                                <td>{{$sp->ma_thuong_hieu}}</td>
                                <td>{{$sp->ma_loai_san_pham}}</td>
                                <td>{{$sp->ten}}</td>
                                <td><img src="{{ $sp->getImage() }}" alt="{{ $sp->hinh_anh }}" class="image-show"></td>
                                <td>{{$sp->don_vi}}</td>
                                <td>{{$sp->don_gia_nhap}}</td>
                                <td>{{$sp->don_gia_ban}}</td>
                                {{-- <td>{{$sp->ma_san_pham_cha}}</td> --}}
                                <td>
                                    <a href=""><button type="button" class="btn btn-success">DETAIL</button></a>
                                    <a href="{{ route('sanpham.edit', $sp->id) }}"><button type="button" class="btn btn-warning">EDIT</button>
                                    <form action="{{ route('sanpham.destroy', $sp->id) }}" method="POST" class="float-left">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">DELETE</button>
                                    </form>
                                </td>
                              </tr>
                            @endforeach
                        </tbody>
                      </table>
                      {{$sanphams->appends(request()->only('key','number'))->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/sanpham/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Vai tro thu {{$vaitro->id}}</div>

                <div class="card-body">

                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Ma to chuc</th>
                            <th scope="col">Ten vai tro</th>
                            <th scope="col">Mo ta</th>
                            <th scope="col">Muc luong</th>
                          </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">{{$vaitro->id}}</th>
                                <td>{{$vaitro->ma_to_chuc}}</td>
                                <td>{{$vaitro->ten_vai_tro}}</td>
                                <td>{{$vaitro->mo_ta}}</td>
                                <td>{{$vaitro->muc_luong}}</td>
                            </tr>
                        </tbody>
                      </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection