routes/web.php
<?php

use App\Http\Controllers\DonDatController;
use App\Http\Controllers\SanPhamController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/sanpham');
});

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('sanpham')->name('sanpham.')->group(function () {
    $class = SanPhamController::class;
    Route::get('/', [$class, 'index'])->name('index');
    Route::get('/create', [$class, 'create'])->name('create');
    Route::post('/', [$class, 'store'])->name('store');
    //Route::get('/{sanpham}', [$class, 'show'])->name('show');
    Route::put('/{sanpham}', [$class, 'update'])->name('update');
    Route::delete('/{sanpham}', [$class, 'destroy'])->name('destroy');
    Route::get('/{sanpham}/edit', [$class, 'edit'])->name('edit');
});

Route::prefix('dondat')->name('dondat.')->group(function () {
    $class = DonDatController::class;
    Route::get('/', [$class, 'index'])->name('index');
    Route::get('/create', [$class, 'create'])->name('create');
    Route::post('/', [$class, 'store'])->name('store');
    Route::get('/{dondat}', [$class, 'show'])->name('show');
    Route::put('/{dondat}', [$class, 'update'])->name('update');
    Route::delete('/{dondat}', [$class, 'destroy'])->name('destroy');
    Route::get('/{dondat}/edit', [$class, 'edit'])->name('edit');
    Route::post('/them_chi_tiet_don_dat', [$class, 'them_chi_tiet_don_dat'])->name('them_chi_tiet_don_dat');
    Route::delete('/delete/{id}', [$class, 'delete_chi_tiet_don_dat'])->name('delete_chi_tiet_don_dat');
});

app/Models/DonDat.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class DonDat extends Model
{
    use HasFactory;

    protected $table = 'don_dats';

    protected $fillable = [
        'id',
        'ma_khach_hang',
        'thoi_gian',
        'ma_nhan_vien',
        'trang_thai',
        'tong_tien',
    ];

    public function san_phams()
    {
        return $this->belongsToMany(SanPham::class, 'chi_tiet_don_dats', 'ma_don_dat', 'ma_san_pham')->withPivot('so_luong');
    }

    public function saveDonDat(Request $data)
    {
        $thoi_gian = Carbon::now();
        $dondat = $this->create([
            'ma_khach_hang' => $data['ma_khach_hang'],
            'thoi_gian' => $thoi_gian,
            'ma_nhan_vien' => $data['ma_nhan_vien'],
            'trang_thai' => 'Chua xac nhan',
            'tong_tien' => '0',
        ]);

        return $dondat;
    }
}

app/Http/Controllers/DonDatController.php
<?php

namespace App\Http\Controllers;

use App\Models\DonDat;
use App\Models\SanPham;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DonDatController extends Controller
{
    protected $dondats;

    public function __construct(DonDat $dondats)
    {
        $this->dondats = $dondats;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dondats = DonDat::all();
        return view('dondat.index', compact('dondats'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $khachhangs = User::where('loai_tai_khoan', 'khach_hang')->get();
        $nhanviens = User::where('loai_tai_khoan', 'nhan_vien')->get();
        return view('dondat.create', compact('khachhangs', 'nhanviens'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'ma_khach_hang' => 'required',
        ]);
        $this->dondats->saveDonDat($request);
        return redirect(route('dondat.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\DonDat  $donDat
     * @return \Illuminate\Http\Response
     */
    public function show(DonDat $dondat)
    {
        $khachhangs = User::where('loai_tai_khoan', 'khach_hang')->get();
        $nhanviens = User::where('loai_tai_khoan', 'nhan_vien')->get();
        $sanphams = SanPham::all();

        $chitiets = DB::table('chi_tiet_don_dats')
        ->join('don_dats', 'chi_tiet_don_dats.ma_don_dat', '=', 'don_dats.id')
        ->join('san_phams', 'chi_tiet_don_dats.ma_san_pham', '=', 'san_phams.id')
        ->where('chi_tiet_don_dats.ma_don_dat', '=', $dondat->id)
        ->select('chi_tiet_don_dats.*', 'san_phams.ten', 'san_phams.don_gia_ban')
        ->orderBy('id', 'DESC')
        ->get();

        return view('dondat.show', compact('dondat', 'sanphams', 'chitiets', 'khachhangs', 'nhanviens'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\DonDat  $donDat
     * @return \Illuminate\Http\Response
     */
    public function edit(DonDat $dondat)
    {
        $khachhangs = User::where('loai_tai_khoan', 'khach_hang')->get();
        $nhanviens = User::where('loai_tai_khoan', 'nhan_vien')->get();
        $sanphams = SanPham::all();

        $chitiets = DB::table('chi_tiet_don_dats')
        ->join('don_dats', 'chi_tiet_don_dats.ma_don_dat', '=', 'don_dats.id')
        ->join('san_phams', 'chi_tiet_don_dats.ma_san_pham', '=', 'san_phams.id')
        ->where('chi_tiet_don_dats.ma_don_dat', '=', $dondat->id)
        ->select('chi_tiet_don_dats.*', 'san_phams.ten', 'san_phams.don_gia_ban')
        ->orderBy('id', 'DESC')
        ->get();

        return view('dondat.edit', compact('dondat', 'sanphams', 'chitiets', 'khachhangs', 'nhanviens'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\DonDat  $donDat
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, DonDat $dondat)
    {
        $dondat->tong_tien = '0';

        $moneys = DB::table('chi_tiet_don_dats')
        ->join('don_dats', 'chi_tiet_don_dats.ma_don_dat', '=', 'don_dats.id')
        ->join('san_phams', 'chi_tiet_don_dats.ma_san_pham', '=', 'san_phams.id')
        ->where('chi_tiet_don_dats.ma_don_dat', '=', $dondat->id)
        ->select('chi_tiet_don_dats.*', 'san_phams.don_gia_ban')
        ->orderBy('id', 'DESC')
        ->get();

        foreach ($moneys as $money) {
            $dondat->tong_tien += $money->so_luong * $money->don_gia_ban;
        }

        $dondat->ma_khach_hang = $request->ma_khach_hang;
        $dondat->thoi_gian = $request->thoi_gian;
        $dondat->ma_nhan_vien = $request->ma_nhan_vien;
        // $dondat->trang_thai = $request->trang_thai;
        $dondat->thoi_gian = Carbon::now();
        $dondat->save();

        return redirect()->back()->with('success', 'Update thành công !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\DonDat  $donDat
     * @return \Illuminate\Http\Response
     */
    public function destroy(DonDat $dondat)
    {
        $dondat->delete();
        return redirect()->route('dondat.index');
    }

    public function them_chi_tiet_don_dat(Request $request)
    {
        $this->validate($request, [
            'ma_san_pham' => 'required|unique:chi_tiet_don_dats',
            'so_luong' => 'required|numeric',
        ]);
        DB::table('chi_tiet_don_dats')->insert([
            'ma_san_pham' => $request->ma_san_pham,
            'ma_don_dat' => $request->ma_don_dat,
            'so_luong' => $request->so_luong]
        );

        return redirect()->back();
        //return redirect()->back()->with('success', 'Thêm thành công!');
    }

    public function delete_chi_tiet_don_dat(int $id)
    {
        DB::table('chi_tiet_don_dats')->where('id', $id)->delete();
        return redirect()->back();
        //return redirect()->back()->with('success', 'Delete thành công!');
    }
}

resources/views/dondat/add_chi_tiet.blade.php
<div class="col">
    <form action="{{ route('dondat.them_chi_tiet_don_dat') }}" method="POST">
        @csrf
        <div class="form-group row">
            {{-- <label for="name" class="col-md-4 col-form-label text-md-right">Vai tro</label> --}}
            <div class="col-md-12 mt-4">
                <div class="container-fluid">
                <h4 class="text-center" style="color:green"> Them san pham </h4>
                <div class="row">
                    <div class="col-md-12">
                        <table class="table" style="background-color:#e0e0e0;" >

                            <thead>
                                <tr>
                                    <th>Ma don dat</th>
                                    <th>San pham</th>
                                    <th>So luong</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody id="">
                                <tr>
                                    <td>
                                        <select name="ma_don_dat" id="ma_don_dat">
                                            <option id={{$dondat->id}} value={{$dondat->id}}>{{$dondat->id}}</option>
                                        </select>
                                    </td>
                                    <td>
                                        <select name="ma_san_pham" id="ma_san_pham" class="form-select @error('ma_san_pham') is-invalid @enderror">
                                        @foreach($sanphams as $sp)
                                            <option id="{{$sp->id}}" value="{{$sp->id}}">
                                                {{$sp->ten}}
                                            </option>
                                        @endforeach
                                        </select>
                                        @error('ma_san_pham')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>Sản phẩm đã tồn tại</strong>
                                            </span>
                                        @enderror
                                    </td>
                                    <td>
                                        <input type="number" id="so_luong" name="so_luong" min="1" value="1" class="form-control @error('so_luong') is-invalid @enderror">
                                        @error('so_luong')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </td>
                                    <td><button id="add" class="btn btn-success">Add</button></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <script>
            $(function(){
                $('#add').on('click',function(){

                    var ma_don_dat = $('select[name="ma_don_dat"]').val();
                    var ma_san_pham = $('select[name="ma_san_pham"]').val();
                    var so_luong = $('input[name="so_luong"]').val();

                    if(ma_don_dat!="" && ma_san_pham!=""){
                        $.ajax({
                            url: location.origin + 'dondat/them_chi_tiet_don_dat',
                            type: "POST",
                            data: {
                                ma_don_dat: ma_don_dat,
                                ma_san_pham: ma_san_pham,
                                so_luong: so_luong,
                            },
                        });
                        // alert('Them vai tro ' + ma_vai_tro + ' !');
                    }
                    else{
                        alert('Vui long nhap day du va chinh xac thong tin !');
                    }

                    //$('#new').append('<tr><td>'+ma_vai_tro+'</td><td>'+tu_ngay+'</td><td>'+den_ngay+'</td><td>'+mo_ta+'</td><td>'+luong_co_ban+'</td><td><button class="btn btn-danger btnDelete">DELETE</button></td></tr>');
                });

                // $('.btnDelete').on('click',function(){
                //     $(this).closest("tr").remove();
                // });
            });
        </script>
    </form>
    {{-- form them / form list --}}
    <div class="col-md-12  mt-4" style="background-color:#f5f5f5;">
        <div class="p-4">
            <div class="text-center">
                <h4>Cac san pham da chon </h4>
            </div>
        </div>
        <table id="" class="table">
            <thead>
                <tr>
                    <!-- <th>ID</th> -->
                    {{-- <th>Don dat</th> --}}
                    <th>San pham</th>
                    <th>Gia</th>
                    <th>So luong</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="new">
                @foreach ($chitiets as $chitiet)
                <tr>
                    <!-- <td>{{$chitiet->id}}</td> -->
                    {{-- <td>{{$chitiet->ma_don_dat}}</td> --}}
                    <td>{{$chitiet->ten}}</td>
                    <td>{{$chitiet->don_gia_ban}} $</td>
                    <td>{{$chitiet->so_luong}}</td>
                    <td>
                        <form action="{{ route('dondat.delete_chi_tiet_don_dat', $chitiet->id) }}" method="POST" class="float-left">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger btnDelete">DELETE</button>
                        </form>
                    </td>
                    {{-- <td><button class="btn btn-danger btnDelete">DELETE</button></td> --}}
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div>
        <h3>Tong tien: {{$dondat->tong_tien}} $</h3>
    </div>
    {{-- Jquery --}}
</div>

resources/views/dondat/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Them moi don dat</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('dondat.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-lg-3 col-form-label text-lg-right">Khach hang</label>
                            <div class="col-lg-6">
                                <select name="ma_khach_hang" id="ma_khach_hang" class="form-select">
                                    <option value="" class="vegitable custom-select">Chon khach hang</option>
                                    @foreach($khachhangs as $kh)
                                    <option id="{{$kh->id}}" value="{{$kh->id}}" class="vegitable custom-select @error('ma_khach_hang') is-invalid @enderror">
                                        {{$kh->name}}
                                        @error('ma_khach_hang')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <br>
                        <div class="form-group row">
                            <label for="name" class="col-lg-3 col-form-label text-lg-right">Nhan vien</label>
                            <div class="col-lg-6">
                                <select name="ma_nhan_vien" id="ma_nhan_vien" class="form-select">
                                    <option value="" class="vegitable custom-select">Chon nhan vien</option>
                                    @foreach($nhanviens as $nv)
                                        <option id="{{$nv->id}}" value="{{$kh->id}}" class="vegitable custom-select">
                                            {{$nv->name}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <br>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Them
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dondat/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-12">
            <div class="card">
                @if (session('success'))
                <div class="alert alert-success">
                    <p>{{ session('success') }}</p>
                </div>
                @endif
                <div class="card-header"></div>

                <div class="card-body">
                    <form action="{{ route('dondat.update', $dondat) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col">
                                <div class="form-group row">
                                    <label for="name" class="col-lg-3 col-form-label text-lg-right">Khach hang</label>
                                    <div class="col-lg-6">
                                        <select name="ma_khach_hang" id="ma_khach_hang" class="form-select">
                                            @foreach($khachhangs as $kh)
                                                <option id="{{$kh->id}}" value="{{$kh->id}}" class="vegitable custom-select"
                                                @if($dondat->ma_khach_hang == $kh->id) selected @endif>
                                                    {{$kh->name}}
                                                </option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <!-- <div class="form-group row">
                                    <label for="name" class="col-lg-3 col-form-label text-lg-right">Nhan vien</label>
                                    <div class="col-lg-6">
                                        <select name="ma_nhan_vien" id="ma_nhan_vien" class="form-select">
                                            @foreach($nhanviens as $nv)
                                                <option id="{{$nv->id}}" value="{{$nv->id}}" class="vegitable custom-select">
                                                    {{$nv->name}}
                                                </option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div> -->
                                <!-- <div class="form-group row">
                                    <label for="name" class="col-lg-3 col-form-label text-lg-right">Trang thai</label>
                                    <div class="col-lg-6">
                                        <select name="trang_thai" class="form-select">
                                            <option value="Chua xac nhan" @if($dondat->trang_thai == 'Chua xac nhan') selected @endif>Chua xac nhan</option>
                                            <option value="Da xac nhan" @if($dondat->trang_thai == 'Da xac nhan') selected @endif>Da xac nhan</option>
                                            <option value="Da thanh toan" @if($dondat->trang_thai == 'Da thanh toan') selected @endif>Da thanh toan</option>
                                        </select>
                                    </div>
                                </div> -->
                                <button id="update" type="submit" class="btn btn-warning">
                                    Update
                                </button>
                            </div>
                        </div>
                    </form>
                    @include('dondat.add_chi_tiet')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dondat/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">

        <div class="col-md-12">
            <h1 class="mt-4">Đơn đặt</h1>
            <!-- <ol class="breadcrumb mb-4">
                <li class="breadcrumb-item active">Welcome to Quan ly don dat !!</li>
            </ol> -->
            <div class="card">
                <!-- <div class="card-header">
                    <a href="{{ route('dondat.create') }}" class="btn btn-primary">Them moi don dat</a>
                </div> -->
                <form action="{{ route('dondat.index') }}" method="GET" class="md-3 d-flex">
                    <input type="text" class="form-control" name="key" value="{{request('key')}}">
                    <button class="btn btn-primary" type="submit">Search</button>
                </form>
                <div class="card-body">

                    <table class="table">
                        <thead>
                          <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Ma khach hang</th>
                            <!-- <th scope="col">Ma nhan vien</th> -->
                            <th scope="col">Thoi gian</th>
                            <!-- <th scope="col">Trang thai</th> -->
                            <th scope="col">Tong tien</th>
                            <th scope="col">Actions</th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($dondats as $dondat)
                            <tr>
                                <th scope="row"><a href="{{ route('dondat.show', $dondat->id) }}">{{$dondat->id}}</a></th>
                                <td>{{$dondat->ma_khach_hang}}</td>
                                <!-- <td>{{$dondat->ma_nhan_vien}}</td> -->
                                <td>{{$dondat->thoi_gian}}</td>
                                <!-- <td>{{$dondat->trang_thai}}</td> -->
                                <td>{{$dondat->tong_tien}}</td>
                                {{-- <td>{{$dondat->vai_tros()->pluck('ten_vai_tro')->last()}}</td> --}}
                                {{-- <td>{{ implode(', ', $dondat->vai_tros()->get()->pluck('ten_vai_tro')->toArray()) }}</td> --}}
                                <td>
                                    <a href="{{ route('dondat.show', $dondat->id) }}"><button type="button" class="btn btn-success">DETAIL</button></a>
                                    <a href="{{ route('dondat.edit', $dondat->id) }}"><button type="button" class="btn btn-warning">EDIT</button></a>
                                    <form action="{{ route('dondat.destroy', $dondat->id) }}" method="POST" class="float-left">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">DELETE</button>
                                    </form>
                                </td>
                              </tr>
                            @endforeach
                        </tbody>
                      </table>
                      {{-- {{$dondats->appends(request()->only('key','number'))->links()}} --}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dondat/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-12">
            <div class="card">
                @if (session('success'))
                <div class="alert alert-success">
                    <p>{{ session('success') }}</p>
                </div>
                @endif
                <div class="card-header"></div>

                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            <div class="form-group row">
                                <label for="name" class="col-lg-3 col-form-label text-lg-right">Khach hang</label>
                                <div class="col-lg-6">
                                    <select name="ma_khach_hang" id="ma_khach_hang" class="form-control">
                                        <option value="{{$dondat->ma_khach_hang}}" class="vegitable custom-select">
                                        {{$dondat->ma_khach_hang}}
                                        </option>
                                    </select>
                                </div>
                            </div>
                            <!-- <div class="form-group row">
                                <label for="name" class="col-lg-3 col-form-label text-lg-right">Nhan vien</label>
                                <div class="col-lg-6">
                                <select name="ma_khach_hang" id="ma_khach_hang" class="form-control">
                                        <option value="{{$dondat->ma_nhan_vien}}" class="vegitable custom-select">
                                        {{$dondat->ma_nhan_vien}}
                                        </option>
                                    </select>
                                </div>
                            </div> -->
                            <!-- <div class="form-group row">
                                <label for="name" class="col-lg-3 col-form-label text-lg-right">Trang thai</label>
                                <div class="col-lg-6">
                                    <select name="trang_thai" class="form-control">
                                        <option value="">{{$dondat->trang_thai}}</option>
                                    </select>
                                </div>
                            </div> -->
                            <div class="form-group row">
                                <label for="name" class="col-lg-3 col-form-label text-lg-right">Thoi gian</label>
                                <div class="col-lg-6">
                                    <select name="trang_thai" class="form-control">
                                        <option value="">{{$dondat->thoi_gian}}</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="col-md-12  mt-4" style="background-color:#f5f5f5;">
                            <div class="p-4">
                                <div class="text-center">
                                    <h4>Cac san pham</h4>
                                </div>
                            </div>
                            <table id="" class="table">
                                <thead>
                                    <tr>
                                        <!-- <th>ID</th> -->
                                        {{-- <th>Don dat</th> --}}
                                        <th>San pham</th>
                                        <th>Gia</th>
                                        <th>So luong</th>
                                    </tr>
                                </thead>
                                <tbody id="new">
                                    @foreach ($chitiets as $chitiet)
                                    <tr>
                                        <!-- <td>{{$chitiet->id}}</td> -->
                                        {{-- <td>{{$chitiet->ma_don_dat}}</td> --}}
                                        <td>{{$chitiet->ten}}</td>
                                        <td>{{$chitiet->don_gia_ban}} $</td>
                                        <td>{{$chitiet->so_luong}}</td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div>
                            <h3>Tong tien: {{$dondat->tong_tien}} $</h3>
                        </div>
                        {{-- Jquery --}}
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection